### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jkells** [dsturnbull/sysuuid#1]
Hi,

This Gem doesn't work on Windows.

**Comment by dsturnbull** [comment]
Are you using IronRuby?

**Comment by jkells** [comment]
Nah, using rubyinstaller. It's native ruby compiled with MinGW.
It's just missing e2fsprogs. I could probably install a -dev package for
that.

On Thu, May 24, 2012 at 2:24 PM, David Turnbull <
reply@reply.github.com

**Comment by dsturnbull** [comment]
Yep, you could do that, but I reckon it'd be much nicer to #ifdef around the code and make a proper win32 native version.
I'll happily accept either, though :)

**Comment by jkells** [comment]
I started but my environment is so broken that I gave up. A big mix of Cygwin, MinGW, Git for Windows and RubyInstaller.
I have 4 copies of bash.exe in my path and none of the tools talk to each other.

Half the shit is compiled against the Windows C runtime, half against the Cygwin runtime it's a mess.

Windows is a mess

I give up.

**Comment by dsturnbull** [comment]
That's basically what happened a few years ago when I tried porting this lib.
You can probably get further faster by shelling out to a C# app that uses the win32 guid lib stuff.
The only reason for this gem is when you need to get uuids thousands of times per second and shelling out was too slow.

**Comment by dsturnbull** [comment]
lol
